package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallDoorstore;
import org.linlinjava.litemall.db.domain.LitemallDoorstoreExample;

public interface LitemallDoorstoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    long countByExample(LitemallDoorstoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallDoorstoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    int insert(LitemallDoorstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    int insertSelective(LitemallDoorstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallDoorstore selectOneByExample(LitemallDoorstoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallDoorstore selectOneByExampleSelective(@Param("example") LitemallDoorstoreExample example, @Param("selective") LitemallDoorstore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallDoorstore> selectByExampleSelective(@Param("example") LitemallDoorstoreExample example, @Param("selective") LitemallDoorstore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    List<LitemallDoorstore> selectByExample(LitemallDoorstoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallDoorstore selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") LitemallDoorstore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    LitemallDoorstore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallDoorstore selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallDoorstore record, @Param("example") LitemallDoorstoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallDoorstore record, @Param("example") LitemallDoorstoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallDoorstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallDoorstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallDoorstoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long id);
}