package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallDoorstore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.ad_code
     *
     * @mbg.generated
     */
    private String adCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.doorstore_name
     *
     * @mbg.generated
     */
    private String doorstoreName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.doorstore_address
     *
     * @mbg.generated
     */
    private String doorstoreAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.doorstore_logo
     *
     * @mbg.generated
     */
    private String doorstoreLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.linkman
     *
     * @mbg.generated
     */
    private String linkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.linkman_phone
     *
     * @mbg.generated
     */
    private String linkmanPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_doorstore.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.id
     *
     * @return the value of litemall_doorstore.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.id
     *
     * @param id the value for litemall_doorstore.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.ad_code
     *
     * @return the value of litemall_doorstore.ad_code
     *
     * @mbg.generated
     */
    public String getAdCode() {
        return adCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.ad_code
     *
     * @param adCode the value for litemall_doorstore.ad_code
     *
     * @mbg.generated
     */
    public void setAdCode(String adCode) {
        this.adCode = adCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.doorstore_name
     *
     * @return the value of litemall_doorstore.doorstore_name
     *
     * @mbg.generated
     */
    public String getDoorstoreName() {
        return doorstoreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.doorstore_name
     *
     * @param doorstoreName the value for litemall_doorstore.doorstore_name
     *
     * @mbg.generated
     */
    public void setDoorstoreName(String doorstoreName) {
        this.doorstoreName = doorstoreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.doorstore_address
     *
     * @return the value of litemall_doorstore.doorstore_address
     *
     * @mbg.generated
     */
    public String getDoorstoreAddress() {
        return doorstoreAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.doorstore_address
     *
     * @param doorstoreAddress the value for litemall_doorstore.doorstore_address
     *
     * @mbg.generated
     */
    public void setDoorstoreAddress(String doorstoreAddress) {
        this.doorstoreAddress = doorstoreAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.doorstore_logo
     *
     * @return the value of litemall_doorstore.doorstore_logo
     *
     * @mbg.generated
     */
    public String getDoorstoreLogo() {
        return doorstoreLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.doorstore_logo
     *
     * @param doorstoreLogo the value for litemall_doorstore.doorstore_logo
     *
     * @mbg.generated
     */
    public void setDoorstoreLogo(String doorstoreLogo) {
        this.doorstoreLogo = doorstoreLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.longitude
     *
     * @return the value of litemall_doorstore.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.longitude
     *
     * @param longitude the value for litemall_doorstore.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.latitude
     *
     * @return the value of litemall_doorstore.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.latitude
     *
     * @param latitude the value for litemall_doorstore.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.remark
     *
     * @return the value of litemall_doorstore.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.remark
     *
     * @param remark the value for litemall_doorstore.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.linkman
     *
     * @return the value of litemall_doorstore.linkman
     *
     * @mbg.generated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.linkman
     *
     * @param linkman the value for litemall_doorstore.linkman
     *
     * @mbg.generated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.linkman_phone
     *
     * @return the value of litemall_doorstore.linkman_phone
     *
     * @mbg.generated
     */
    public String getLinkmanPhone() {
        return linkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.linkman_phone
     *
     * @param linkmanPhone the value for litemall_doorstore.linkman_phone
     *
     * @mbg.generated
     */
    public void setLinkmanPhone(String linkmanPhone) {
        this.linkmanPhone = linkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.add_time
     *
     * @return the value of litemall_doorstore.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.add_time
     *
     * @param addTime the value for litemall_doorstore.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.update_time
     *
     * @return the value of litemall_doorstore.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.update_time
     *
     * @param updateTime the value for litemall_doorstore.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_doorstore.deleted
     *
     * @return the value of litemall_doorstore.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_doorstore.deleted
     *
     * @param deleted the value for litemall_doorstore.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", adCode=").append(adCode);
        sb.append(", doorstoreName=").append(doorstoreName);
        sb.append(", doorstoreAddress=").append(doorstoreAddress);
        sb.append(", doorstoreLogo=").append(doorstoreLogo);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", remark=").append(remark);
        sb.append(", linkman=").append(linkman);
        sb.append(", linkmanPhone=").append(linkmanPhone);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallDoorstore other = (LitemallDoorstore) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAdCode() == null ? other.getAdCode() == null : this.getAdCode().equals(other.getAdCode()))
            && (this.getDoorstoreName() == null ? other.getDoorstoreName() == null : this.getDoorstoreName().equals(other.getDoorstoreName()))
            && (this.getDoorstoreAddress() == null ? other.getDoorstoreAddress() == null : this.getDoorstoreAddress().equals(other.getDoorstoreAddress()))
            && (this.getDoorstoreLogo() == null ? other.getDoorstoreLogo() == null : this.getDoorstoreLogo().equals(other.getDoorstoreLogo()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getLinkman() == null ? other.getLinkman() == null : this.getLinkman().equals(other.getLinkman()))
            && (this.getLinkmanPhone() == null ? other.getLinkmanPhone() == null : this.getLinkmanPhone().equals(other.getLinkmanPhone()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAdCode() == null) ? 0 : getAdCode().hashCode());
        result = prime * result + ((getDoorstoreName() == null) ? 0 : getDoorstoreName().hashCode());
        result = prime * result + ((getDoorstoreAddress() == null) ? 0 : getDoorstoreAddress().hashCode());
        result = prime * result + ((getDoorstoreLogo() == null) ? 0 : getDoorstoreLogo().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getLinkman() == null) ? 0 : getLinkman().hashCode());
        result = prime * result + ((getLinkmanPhone() == null) ? 0 : getLinkmanPhone().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_doorstore
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        adCode("ad_code", "adCode", "VARCHAR", false),
        doorstoreName("doorstore_name", "doorstoreName", "VARCHAR", false),
        doorstoreAddress("doorstore_address", "doorstoreAddress", "VARCHAR", false),
        doorstoreLogo("doorstore_logo", "doorstoreLogo", "VARCHAR", false),
        longitude("longitude", "longitude", "DOUBLE", false),
        latitude("latitude", "latitude", "DOUBLE", false),
        remark("remark", "remark", "VARCHAR", false),
        linkman("linkman", "linkman", "VARCHAR", false),
        linkmanPhone("linkman_phone", "linkmanPhone", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_doorstore
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}