spring:
  profiles:
    active: dbdev, core, admin, wx
  messages:
    encoding: UTF-8

server:
  port: 8080

logging:
  level:
    root:  info
    org.springframework:  ERROR
    org.mybatis:  debug
    org.linlinjava.litemall.core:  ERROR
    org.linlinjava.litemall.db:  debug
    org.linlinjava.litemall.admin:  ERROR
    org.linlinjava.litemall.wx:  ERROR
    org.linlinjava.litemall:  ERROR